# Generated by Django 4.2 on 2023-04-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmospheres', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_library',
            field=models.ManyToManyField(related_name='put_in_library', to='atmospheres.atmosphere'),
        ),
    ]
