# Generated by Django 4.2 on 2023-04-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmospheres', '0003_atmosphere_date_created'),
        ('users', '0004_alter_user_user_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_library',
            field=models.ManyToManyField(blank=True, related_name='put_in_library', to='atmospheres.atmosphere'),
        ),
    ]
