# Generated by Django 4.2 on 2023-04-18 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_user_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.URLField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
