# Generated by Django 4.2 on 2023-04-15 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atmosphere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('audio', models.URLField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
