# Generated by Django 4.2 on 2023-04-15 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atmospheres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmosphere',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_atmospheres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atmosphere',
            name='tags',
            field=models.ManyToManyField(related_name='atmospheres', to='tags.tag'),
        ),
    ]
