# Generated by Django 4.2 on 2023-04-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmospheres', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmosphere',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-03-23 18:00:00'),
            preserve_default=False,
        ),
    ]
