# Generated by Django 4.2 on 2023-04-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmospheres', '0003_atmosphere_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmosphere',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
